name = "yurakuna-api"
main = "index.ts"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[vars]
# Variables de entorno públicas (sin datos sensibles)
JWT_EXPIRES_IN = "15m"
JWT_REFRESH_EXPIRES_IN = "7d"
CORS_ORIGINS = "https://yurakuna-front.pablo-guallichico.workers.dev,https://yurakuna.frubest.com,http://localhost:4200"

# Secrets - configurar con: wrangler secret put <NAME>
# DATABASE_URL
# JWT_SECRET
# JWT_REFRESH_SECRET

# Para desarrollo local
[env.development]
name = "yurakuna-api-dev"

# Para producción
[env.production]
name = "yurakuna-api-prod"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "3b0a55001130450889cc8122d18cbfab"